# TCL File Generated by Component Editor 18.1
# Fri Dec 24 11:46:00 CET 2021
# DO NOT MODIFY


# 
# LCD_controller "LCD_controller" v1.0
# Yassine Bakkali, Thanh Vinh Vincent Nguyen 2021.12.24.11:46:00
# Controller for the LT24 LCD displayer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_controller
# 
set_module_property DESCRIPTION "Controller for the LT24 LCD displayer"
set_module_property NAME LCD_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP custom_PIs
set_module_property AUTHOR "Yassine Bakkali, Thanh Vinh Vincent Nguyen"
set_module_property DISPLAY_NAME LCD_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file LCD_controller.vhd VHDL PATH ../hdl/LCD_controller.vhd TOP_LEVEL_FILE
add_fileset_file LT24_Interface.vhd VHDL PATH ../hdl/LT24_Interface.vhd
add_fileset_file Master_Interface_DMA.vhd VHDL PATH ../hdl/Master_Interface_DMA.vhd
add_fileset_file Slave_Interface.vhd VHDL PATH ../hdl/Slave_Interface.vhd
add_fileset_file FIFO_entity.vhd VHDL PATH ../hdl/FIFO_entity.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL LCD_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file LCD_controller.vhd VHDL PATH ../hdl/LCD_controller.vhd
add_fileset_file LT24_Interface.vhd VHDL PATH ../hdl/LT24_Interface.vhd
add_fileset_file Master_Interface_DMA.vhd VHDL PATH ../hdl/Master_Interface_DMA.vhd
add_fileset_file Slave_Interface.vhd VHDL PATH ../hdl/Slave_Interface.vhd
add_fileset_file FIFO_entity.vhd VHDL PATH ../hdl/FIFO_entity.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end LT24_Res_n res_n Output 1
add_interface_port conduit_end LT24_CSX csx Output 1
add_interface_port conduit_end LT24_WRX wrx Output 1
add_interface_port conduit_end LT24_RDX rdx Output 1
add_interface_port conduit_end LT24_D d Output 16
add_interface_port conduit_end LT24_DCX dcx Output 1
add_interface_port conduit_end LT24_LCD_ON lcd_on Output 1


# 
# connection point nReset
# 
add_interface nReset reset end
set_interface_property nReset associatedClock clk
set_interface_property nReset synchronousEdges DEASSERT
set_interface_property nReset ENABLED true
set_interface_property nReset EXPORT_OF ""
set_interface_property nReset PORT_NAME_MAP ""
set_interface_property nReset CMSIS_SVD_VARIABLES ""
set_interface_property nReset SVD_ADDRESS_GROUP ""

add_interface_port nReset nReset reset_n Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset nReset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave as_writedata writedata Input 32
add_interface_port avalon_slave as_write write Input 1
add_interface_port avalon_slave as_address address Input 3
add_interface_port avalon_slave as_read read Input 1
add_interface_port avalon_slave as_readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clk
set_interface_property avalon_master associatedReset nReset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master am_address address Output 32
add_interface_port avalon_master am_burstcount burstcount Output 8
add_interface_port avalon_master am_readdata readdata Input 32
add_interface_port avalon_master am_readdatavalid readdatavalid Input 1
add_interface_port avalon_master am_byteenable byteenable Output 4
add_interface_port avalon_master am_waitrequest waitrequest Input 1
add_interface_port avalon_master am_read read Output 1

